# Generated by Django 5.0.6 on 2024-07-04 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_alter_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='status',
            new_name='job',
        ),
    ]
