# Generated by Django 5.0.6 on 2024-07-05 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_bestemployees_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimage',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.news'),
        ),
    ]
