# Generated by Django 5.0.6 on 2024-07-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_bestemployees_options_alter_evaluation_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fine',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prize',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
